name: Build-Master

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - master

jobs:
  build-debug-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Cysharp/Actions/.github/actions/setup-dotnet@main
        with:
          dotnet-version: |
            3.1.x
            5.0.x
            6.0.x
      - run: dotnet build -c Debug -p:DefineConstants=RUNNING_IN_CI
      - run: dotnet pack ./src/LogicLooper/LogicLooper.csproj -c Debug --no-build -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
      - run: dotnet test -c Debug --no-build
      - uses: actions/upload-artifact@v2
        with:
          path: ./src/LogicLooper/bin/Debug/*.*nupkg
