name: Build-GitHubPages

on:
  push:
    branches:
      - master

jobs:
  run-docfx:
    if: ${{ !(contains(github.event.head_commit.message, '[skip ci]') || contains(github.event.head_commit.message, '[ci skip]')) }}
    permissions:
      contents: write
      pages: write
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: Cysharp/Actions/.github/actions/checkout@main
      - uses: Cysharp/Actions/.github/actions/checkout@main
        with:
          repository: Cysharp/DocfxTemplate
          path: docs/_DocfxTemplate
      - uses: Cysharp/Actions/.github/actions/setup-dotnet@main
      - name: dotnet tool restore
        run: dotnet tool restore
      - name: Docfx metadata
        run: dotnet docfx metadata docs/docfx.json
      - name: Docfx build
        run: dotnet docfx build docs/docfx.json
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_site
