name: Build-Master

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and run tests
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: Cysharp/Actions/.github/actions/checkout@main
      - uses: Cysharp/Actions/.github/actions/setup-dotnet@main
      - run: dotnet build -c Release -p:DefineConstants=RUNNING_IN_CI
      - run: dotnet test -c Release --no-build
      - run: dotnet pack -c Release --no-build  -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg -o artifacts
      - uses: Cysharp/Actions/.github/actions/upload-artifact@main
        with:
          name: nuget
          path: artifacts/*.*nupkg
          retention-days: 1
