name: Build-Master

on:
  push:
    branches:
      - "master"
    tags:
      - "!*" # not a tag push
  pull_request:
    branches:
      - master

env:
  DOTNET_SDK_VERISON_3: 3.1.x

jobs:
  build-debug-test:
    if: "!(contains(github.event.head_commit.message, '[skip ci]') || contains(github.event.head_commit.message, '[ci skip]'))"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERISON_3 }}
      - run: dotnet build -c Debug -p:DefineConstants=RUNNING_IN_CI
      - run: dotnet pack ./src/LogicLooper/LogicLooper.csproj -c Debug --no-build -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
      - run: dotnet test -c Debug --no-build
      - uses: actions/upload-artifact@v2
        with:
          path: ./src/LogicLooper/bin/Debug/*.*nupkg
