name: Build-Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*" # only tag

jobs:
  build-release:
    if: "!(contains(github.event.head_commit.message, '[skip ci]') || contains(github.event.head_commit.message, '[ci skip]'))"
    steps:
      - uses: actions/checkout@v2
      - run: echo ::set-env name=GIT_TAG::${GITHUB_REF#refs/tags/}
      - run: dotnet build -c Release -p:VersionPrefix=${{ env.GIT_TAG }} -p:DefineConstants=RUNNING_IN_CI
      - run: dotnet test -c Release --no-build
      - run: dotnet pack ./src/LogicLooper/LogicLooper.csproj -c Release --no-build -p:VersionPrefix=${{ env.GIT_TAG }} -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
      - run: dotnet nuget push ./src/LogicLooper/bin/Release/LogicLooper.${{ env.GIT_TAG }}.nupkg -s https://www.nuget.org/api/v2/package -k $${{ secrets.NUGET_KEY }}
      - run: dotnet nuget push ./src/LogicLooper/bin/Release/LogicLooper.${{ env.GIT_TAG }}.snupkg -s https://www.nuget.org/api/v2/package -k ${{ secrets.NUGET_KEY }}