name: Build-Master

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - master

jobs:
  build-debug:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Cysharp/Actions/.github/actions/setup-dotnet@main
      - run: dotnet build -c Debug -p:DefineConstants=RUNNING_IN_CI
      - run: dotnet pack ./src/LogicLooper/LogicLooper.csproj -c Debug --no-build -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
      - run: dotnet test -c Debug --no-build
      - uses: actions/upload-artifact@v4
        with:
          path: ./src/LogicLooper/bin/Debug/*.*nupkg
  test-release-build:
    name: Run tests using Release build
    needs: [ build-debug ]
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: Cysharp/Actions/.github/actions/setup-dotnet@main
      - run: dotnet build -c Release -p:DefineConstants=RUNNING_IN_CI
      - run: dotnet test -c Release --no-build
